CREATE TABLE portfolio_holdings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    stock_id BIGINT NOT NULL REFERENCES stocks(id),
    quantity NUMERIC(20, 6) NOT NULL,
    average_purchase_price NUMERIC(20, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_holdings_user_stock UNIQUE (user_id, stock_id),
    CONSTRAINT ck_portfolio_holdings_quantity CHECK (quantity > 0),
    CONSTRAINT ck_portfolio_holdings_average_price CHECK (average_purchase_price >= 0)
);

CREATE INDEX idx_portfolio_holdings_user ON portfolio_holdings (user_id, created_at);
