CREATE TABLE price_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    stock_id BIGINT NOT NULL REFERENCES stocks(id),
    alert_condition VARCHAR(10) NOT NULL,
    target_price NUMERIC(20, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(12) NOT NULL,
    triggered_at TIMESTAMP WITH TIME ZONE,
    last_evaluated_price NUMERIC(20, 4),
    last_evaluated_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_price_alerts_condition CHECK (alert_condition IN ('ABOVE', 'BELOW')),
    CONSTRAINT ck_price_alerts_status CHECK (status IN ('ACTIVE', 'TRIGGERED', 'DISABLED')),
    CONSTRAINT ck_price_alerts_target CHECK (target_price > 0)
);

CREATE INDEX idx_price_alerts_user_created ON price_alerts (user_id, created_at);
CREATE INDEX idx_price_alerts_active_stock ON price_alerts (stock_id, status);
