CREATE TABLE ai_technical_explanations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES stocks(id),
    analysis_interval VARCHAR(10) NOT NULL,
    latest_recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    calculation_version VARCHAR(80) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    source VARCHAR(50) NOT NULL,
    freshness VARCHAR(20) NOT NULL,
    summary_signal VARCHAR(20) NOT NULL,
    summary TEXT NOT NULL,
    trend_explanation TEXT NOT NULL,
    momentum_explanation TEXT NOT NULL,
    volatility_explanation TEXT NOT NULL,
    volume_explanation TEXT NOT NULL,
    supporting_signals TEXT NOT NULL,
    conflicting_signals TEXT NOT NULL,
    risk_notes TEXT NOT NULL,
    data_limitations TEXT NOT NULL,
    evidence TEXT NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    estimated_cost NUMERIC(16, 8) NOT NULL,
    cache_key VARCHAR(500) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_ai_technical_snapshot UNIQUE (
        stock_id, analysis_interval, latest_recorded_at, calculation_version, input_hash, prompt_version
    ),
    CONSTRAINT uk_ai_technical_cache_key UNIQUE (cache_key)
);

CREATE INDEX idx_ai_technical_stock_generated
    ON ai_technical_explanations (stock_id, generated_at DESC);

ALTER TABLE ai_usage_logs
    ADD COLUMN technical_explanation_id BIGINT REFERENCES ai_technical_explanations(id);

CREATE INDEX idx_ai_usage_logs_technical_explanation
    ON ai_usage_logs (technical_explanation_id);
