ALTER TABLE stocks ADD COLUMN exchange VARCHAR(30);
ALTER TABLE stocks ADD COLUMN english_name VARCHAR(150);
ALTER TABLE stocks ADD COLUMN normalized_name VARCHAR(150);
ALTER TABLE stocks ADD COLUMN normalized_english_name VARCHAR(150);
ALTER TABLE stocks ADD COLUMN instrument_type VARCHAR(30);
ALTER TABLE stocks ADD COLUMN provider VARCHAR(50);
ALTER TABLE stocks ADD COLUMN provider_instrument_id VARCHAR(100);
ALTER TABLE stocks ADD COLUMN isin VARCHAR(20);
ALTER TABLE stocks ADD COLUMN tradable BOOLEAN;
ALTER TABLE stocks ADD COLUMN status VARCHAR(30);
ALTER TABLE stocks ADD COLUMN listed_at DATE;
ALTER TABLE stocks ADD COLUMN delisted_at DATE;
ALTER TABLE stocks ADD COLUMN catalog_updated_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE stocks ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;

UPDATE stocks
SET exchange = market,
    english_name = CASE symbol
        WHEN '005930' THEN 'Samsung Electronics'
        WHEN '000660' THEN 'SK hynix'
        WHEN 'NVDA' THEN 'NVIDIA Corporation'
        WHEN 'AAPL' THEN 'Apple Inc.'
        ELSE name
    END,
    normalized_name = LOWER(REPLACE(name, ' ', '')),
    normalized_english_name = LOWER(REPLACE(CASE symbol
        WHEN '005930' THEN 'Samsung Electronics'
        WHEN '000660' THEN 'SK hynix'
        WHEN 'NVDA' THEN 'NVIDIA Corporation'
        WHEN 'AAPL' THEN 'Apple Inc.'
        ELSE name
    END, ' ', '')),
    instrument_type = 'STOCK',
    provider = CASE WHEN market = 'KRX' THEN 'KIS_MASTER' ELSE 'FINNHUB_SYMBOLS' END,
    provider_instrument_id = market || ':' || symbol,
    tradable = TRUE,
    status = 'LISTED',
    catalog_updated_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP;

ALTER TABLE stocks ALTER COLUMN exchange SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN normalized_name SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN instrument_type SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN provider SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN provider_instrument_id SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN tradable SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN status SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN catalog_updated_at SET NOT NULL;
ALTER TABLE stocks ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE stocks ADD CONSTRAINT uk_stocks_provider_instrument UNIQUE (provider, provider_instrument_id);

CREATE INDEX idx_stocks_symbol ON stocks (symbol);
CREATE INDEX idx_stocks_normalized_name ON stocks (normalized_name);
CREATE INDEX idx_stocks_normalized_english_name ON stocks (normalized_english_name);
CREATE INDEX idx_stocks_catalog_filter ON stocks (active, market, instrument_type);

CREATE TABLE stock_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES stocks(id),
    alias VARCHAR(150) NOT NULL,
    normalized_alias VARCHAR(150) NOT NULL,
    alias_type VARCHAR(30) NOT NULL,
    CONSTRAINT uk_stock_alias UNIQUE (stock_id, normalized_alias)
);

CREATE INDEX idx_stock_alias_normalized ON stock_aliases (normalized_alias);

CREATE TABLE instrument_catalog_sync_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(50) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(30) NOT NULL,
    received_count INTEGER NOT NULL DEFAULT 0,
    inserted_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    deactivated_count INTEGER NOT NULL DEFAULT 0,
    error_code VARCHAR(80),
    error_message VARCHAR(500)
);

INSERT INTO stocks (
    symbol, name, market, currency, active, exchange, english_name,
    normalized_name, normalized_english_name, instrument_type, provider,
    provider_instrument_id, tradable, status, catalog_updated_at, updated_at
)
VALUES
    ('035420', 'NAVER', 'KRX', 'KRW', TRUE, 'KRX', 'NAVER Corporation', 'naver', 'navercorporation', 'STOCK', 'KIS_MASTER', 'KRX:035420', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('035720', '카카오', 'KRX', 'KRW', TRUE, 'KRX', 'Kakao Corporation', '카카오', 'kakaocorporation', 'STOCK', 'KIS_MASTER', 'KRX:035720', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('207940', '삼성바이오로직스', 'KRX', 'KRW', TRUE, 'KRX', 'Samsung Biologics', '삼성바이오로직스', 'samsungbiologics', 'STOCK', 'KIS_MASTER', 'KRX:207940', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('005380', '현대자동차', 'KRX', 'KRW', TRUE, 'KRX', 'Hyundai Motor Company', '현대자동차', 'hyundaimotorcompany', 'STOCK', 'KIS_MASTER', 'KRX:005380', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('068270', '셀트리온', 'KRX', 'KRW', TRUE, 'KRX', 'Celltrion', '셀트리온', 'celltrion', 'STOCK', 'KIS_MASTER', 'KRX:068270', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('MSFT', 'Microsoft', 'NASDAQ', 'USD', TRUE, 'NASDAQ', 'Microsoft Corporation', 'microsoft', 'microsoftcorporation', 'STOCK', 'FINNHUB_SYMBOLS', 'NASDAQ:MSFT', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('GOOGL', 'Alphabet', 'NASDAQ', 'USD', TRUE, 'NASDAQ', 'Alphabet Inc.', 'alphabet', 'alphabetinc.', 'STOCK', 'FINNHUB_SYMBOLS', 'NASDAQ:GOOGL', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('AMZN', 'Amazon', 'NASDAQ', 'USD', TRUE, 'NASDAQ', 'Amazon.com Inc.', 'amazon', 'amazon.cominc.', 'STOCK', 'FINNHUB_SYMBOLS', 'NASDAQ:AMZN', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('META', 'Meta Platforms', 'NASDAQ', 'USD', TRUE, 'NASDAQ', 'Meta Platforms Inc.', 'metaplatforms', 'metaplatformsinc.', 'STOCK', 'FINNHUB_SYMBOLS', 'NASDAQ:META', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TSLA', 'Tesla', 'NASDAQ', 'USD', TRUE, 'NASDAQ', 'Tesla Inc.', 'tesla', 'teslainc.', 'STOCK', 'FINNHUB_SYMBOLS', 'NASDAQ:TSLA', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('BRK.B', 'Berkshire Hathaway', 'NYSE', 'USD', TRUE, 'NYSE', 'Berkshire Hathaway Inc. Class B', 'berkshirehathaway', 'berkshirehathawayinc.classb', 'STOCK', 'FINNHUB_SYMBOLS', 'NYSE:BRK.B', TRUE, 'LISTED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TEST', 'Demo Technologies', 'NASDAQ', 'USD', TRUE, 'NASDAQ', 'Demo Technologies', 'demotechnologies', 'demotechnologies', 'STOCK', 'DEMO_CATALOG', 'NASDAQ:TEST', FALSE, 'DEMO_ONLY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('TEST', 'Demo Holdings', 'NYSE', 'USD', TRUE, 'NYSE', 'Demo Holdings', 'demoholdings', 'demoholdings', 'STOCK', 'DEMO_CATALOG', 'NYSE:TEST', FALSE, 'DEMO_ONLY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO stock_aliases (stock_id, alias, normalized_alias, alias_type)
VALUES
    ((SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '005930'), '삼성', '삼성', 'SHORT_NAME'),
    ((SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '005930'), 'Samsung', 'samsung', 'ENGLISH_ALIAS'),
    ((SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '000660'), '하이닉스', '하이닉스', 'SHORT_NAME'),
    ((SELECT id FROM stocks WHERE market = 'NASDAQ' AND symbol = 'AAPL'), '애플', '애플', 'LOCALIZED_NAME'),
    ((SELECT id FROM stocks WHERE market = 'NASDAQ' AND symbol = 'GOOGL'), 'Google', 'google', 'FORMER_NAME'),
    ((SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '005380'), '현대차', '현대차', 'SHORT_NAME');

INSERT INTO instrument_catalog_sync_runs (
    provider, started_at, finished_at, status, received_count, inserted_count, updated_count, deactivated_count
)
VALUES
    ('DEMO_CATALOG', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SUCCEEDED', 17, 13, 4, 0);
