CREATE TABLE exchange_rates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_currency VARCHAR(3) NOT NULL,
    quote_currency VARCHAR(3) NOT NULL,
    rate NUMERIC(24, 10) NOT NULL,
    open_rate NUMERIC(24, 10),
    high_rate NUMERIC(24, 10),
    low_rate NUMERIC(24, 10),
    close_rate NUMERIC(24, 10),
    rate_type VARCHAR(20) NOT NULL,
    source VARCHAR(50) NOT NULL,
    provider_symbol VARCHAR(100),
    as_of TIMESTAMP WITH TIME ZONE NOT NULL,
    fetched_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_exchange_rates_pair_source_time UNIQUE (base_currency, quote_currency, source, as_of),
    CONSTRAINT ck_exchange_rates_pair CHECK (base_currency <> quote_currency),
    CONSTRAINT ck_exchange_rates_positive CHECK (rate > 0)
);

CREATE INDEX idx_exchange_rates_pair_time
    ON exchange_rates (base_currency, quote_currency, as_of DESC);

ALTER TABLE portfolio_holdings ADD COLUMN average_purchase_fx_rate NUMERIC(24, 10);
ALTER TABLE portfolio_holdings ADD COLUMN purchase_fx_base_currency VARCHAR(3);
ALTER TABLE portfolio_holdings ADD COLUMN purchase_fx_quote_currency VARCHAR(3);

ALTER TABLE portfolio_holdings ADD CONSTRAINT ck_portfolio_purchase_fx_complete CHECK (
    (average_purchase_fx_rate IS NULL AND purchase_fx_base_currency IS NULL AND purchase_fx_quote_currency IS NULL)
    OR
    (average_purchase_fx_rate > 0 AND purchase_fx_base_currency IS NOT NULL AND purchase_fx_quote_currency IS NOT NULL
        AND purchase_fx_base_currency <> purchase_fx_quote_currency)
);

INSERT INTO exchange_rates (
    base_currency, quote_currency, rate, open_rate, high_rate, low_rate, close_rate,
    rate_type, source, provider_symbol, as_of, fetched_at, created_at
) VALUES
('USD', 'KRW', 1378.2000000000, 1372.1000000000, 1381.4000000000, 1370.8000000000, 1378.2000000000, 'DEMO', 'DEMO', 'DEMO:USD_KRW', TIMESTAMP WITH TIME ZONE '2026-07-10 06:00:00+00', TIMESTAMP WITH TIME ZONE '2026-07-10 06:00:05+00', CURRENT_TIMESTAMP),
('USD', 'KRW', 1380.6000000000, 1378.2000000000, 1384.1000000000, 1376.9000000000, 1380.6000000000, 'DEMO', 'DEMO', 'DEMO:USD_KRW', TIMESTAMP WITH TIME ZONE '2026-07-13 06:00:00+00', TIMESTAMP WITH TIME ZONE '2026-07-13 06:00:05+00', CURRENT_TIMESTAMP),
('USD', 'KRW', 1382.5000000000, 1380.6000000000, 1385.2000000000, 1379.7000000000, 1382.5000000000, 'DEMO', 'DEMO', 'DEMO:USD_KRW', TIMESTAMP WITH TIME ZONE '2026-07-14 06:00:00+00', TIMESTAMP WITH TIME ZONE '2026-07-14 06:00:05+00', CURRENT_TIMESTAMP);
