CREATE TABLE ai_daily_change_briefings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES stocks(id),
    market VARCHAR(30) NOT NULL,
    current_trading_date DATE NOT NULL,
    previous_trading_date DATE,
    baseline_status VARCHAR(30) NOT NULL,
    latest_recorded_at TIMESTAMP WITH TIME ZONE NOT NULL,
    calculation_version VARCHAR(80) NOT NULL,
    briefing_input_version VARCHAR(80) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    relation VARCHAR(30) NOT NULL,
    headline VARCHAR(120) NOT NULL,
    change_summary TEXT NOT NULL,
    headline_evidence_ids TEXT NOT NULL,
    change_summary_evidence_ids TEXT NOT NULL,
    viewpoints TEXT NOT NULL,
    new_strengths TEXT NOT NULL,
    new_risks TEXT NOT NULL,
    unchanged_context TEXT NOT NULL,
    aligned_views TEXT NOT NULL,
    conflicting_views TEXT NOT NULL,
    data_limitations TEXT NOT NULL,
    evidence TEXT NOT NULL,
    source_summary TEXT NOT NULL,
    evidence_count INTEGER NOT NULL,
    excluded_content_count INTEGER NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    estimated_cost DECIMAL(16, 8) NOT NULL,
    cache_key VARCHAR(500) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_daily_briefing_snapshot UNIQUE (stock_id, current_trading_date, input_hash, prompt_version),
    CONSTRAINT uk_daily_briefing_cache_key UNIQUE (cache_key)
);

CREATE INDEX idx_daily_briefing_stock_generated
    ON ai_daily_change_briefings (stock_id, generated_at DESC);

ALTER TABLE ai_usage_logs ADD COLUMN daily_briefing_id BIGINT;
ALTER TABLE ai_usage_logs ADD CONSTRAINT fk_ai_usage_daily_briefing
    FOREIGN KEY (daily_briefing_id) REFERENCES ai_daily_change_briefings(id);
