ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE users ALTER COLUMN password_hash DROP NOT NULL;

ALTER TABLE users ADD COLUMN display_name VARCHAR(100);
ALTER TABLE users ADD COLUMN profile_image_url VARCHAR(1000);
ALTER TABLE users ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE users ADD COLUMN last_login_at TIMESTAMP WITH TIME ZONE;

UPDATE users
SET display_name = CASE
    WHEN email IS NULL OR POSITION('@' IN email) <= 1 THEN 'FinWatch 사용자'
    ELSE SUBSTRING(email, 1, POSITION('@' IN email) - 1)
END
WHERE display_name IS NULL;

ALTER TABLE users ALTER COLUMN display_name SET NOT NULL;
ALTER TABLE users ADD CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE', 'DISABLED', 'DELETED'));

CREATE TABLE auth_identities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_auth_identities_provider_subject UNIQUE (provider, provider_subject),
    CONSTRAINT chk_auth_identities_provider CHECK (provider IN ('LOCAL', 'KAKAO'))
);

CREATE INDEX idx_auth_identities_user ON auth_identities (user_id);
