CREATE TABLE ai_portfolio_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    snapshot_at TIMESTAMP WITH TIME ZONE NOT NULL,
    window_started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    positions_hash VARCHAR(64) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    balance_status VARCHAR(40) NOT NULL,
    headline VARCHAR(180) NOT NULL,
    summary TEXT NOT NULL,
    diversification TEXT NOT NULL,
    concentration TEXT NOT NULL,
    currency_exposure TEXT NOT NULL,
    performance_context TEXT NOT NULL,
    strengths TEXT NOT NULL,
    risk_factors TEXT NOT NULL,
    review_points TEXT NOT NULL,
    data_limitations TEXT NOT NULL,
    evidence TEXT NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    estimated_cost DECIMAL(16, 8) NOT NULL,
    cache_key VARCHAR(500) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_portfolio_evaluation_cache_key UNIQUE (cache_key),
    CONSTRAINT uk_portfolio_evaluation_window UNIQUE (
        user_id, positions_hash, window_started_at, prompt_version),
    CONSTRAINT ck_portfolio_evaluation_tokens CHECK (
        input_tokens >= 0 AND output_tokens >= 0)
);

CREATE INDEX idx_portfolio_evaluation_user_generated
    ON ai_portfolio_evaluations (user_id, generated_at DESC);

ALTER TABLE ai_usage_logs ADD COLUMN portfolio_evaluation_id BIGINT;
ALTER TABLE ai_usage_logs ADD CONSTRAINT fk_ai_usage_portfolio_evaluation
    FOREIGN KEY (portfolio_evaluation_id)
    REFERENCES ai_portfolio_evaluations(id)
    ON DELETE SET NULL;
