CREATE TABLE news_articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stock_id BIGINT NOT NULL REFERENCES stocks(id),
    external_id VARCHAR(255) NOT NULL,
    title VARCHAR(500) NOT NULL,
    publisher VARCHAR(150),
    url VARCHAR(1000) NOT NULL,
    content TEXT,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL,
    source VARCHAR(50) NOT NULL,
    content_hash VARCHAR(64),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_news_source_external_id UNIQUE (source, external_id)
);

CREATE INDEX idx_news_stock_published_at
    ON news_articles (stock_id, published_at DESC);

CREATE TABLE ai_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id BIGINT NOT NULL REFERENCES news_articles(id),
    feature_type VARCHAR(40) NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    summary TEXT NOT NULL,
    key_points TEXT NOT NULL,
    keywords TEXT NOT NULL,
    sentiment VARCHAR(20) NOT NULL,
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    estimated_cost NUMERIC(16, 8) NOT NULL,
    cache_key VARCHAR(255) NOT NULL,
    generated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_ai_analysis_target_prompt UNIQUE (news_id, feature_type, prompt_version),
    CONSTRAINT uk_ai_analysis_cache_key UNIQUE (cache_key)
);

CREATE TABLE ai_usage_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    user_id BIGINT REFERENCES users(id),
    analysis_id BIGINT REFERENCES ai_analyses(id),
    feature_type VARCHAR(40) NOT NULL,
    target_type VARCHAR(40) NOT NULL,
    target_id BIGINT NOT NULL,
    model_name VARCHAR(100),
    input_tokens INTEGER NOT NULL,
    output_tokens INTEGER NOT NULL,
    estimated_cost NUMERIC(16, 8) NOT NULL,
    saved_estimated_cost NUMERIC(16, 8) NOT NULL,
    cache_hit BOOLEAN NOT NULL,
    response_time_ms INTEGER NOT NULL,
    prompt_version VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL,
    error_code VARCHAR(80),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_ai_usage_logs_created_at ON ai_usage_logs (created_at DESC);
CREATE INDEX idx_ai_usage_logs_feature_created_at ON ai_usage_logs (feature_type, created_at DESC);
CREATE INDEX idx_ai_usage_logs_cost ON ai_usage_logs (estimated_cost DESC);

INSERT INTO news_articles (
    stock_id, external_id, title, publisher, url, content, published_at, source, content_hash
)
VALUES
    (
        (SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '000660'),
        'demo-news-000660-1',
        'SK하이닉스, HBM 수요 증가로 실적 전망 상향',
        'FinWatch Demo News',
        'https://example.com/news/demo-news-000660-1',
        '<p>SK하이닉스의 고대역폭 메모리 HBM 수요가 글로벌 AI 서버 투자 확대와 함께 증가하고 있다.</p> 광고 문의는 제외합니다. 주요 증권사들은 메모리 업황 회복과 고부가 제품 비중 확대를 근거로 실적 전망을 상향했다. 주요 증권사들은 메모리 업황 회복과 고부가 제품 비중 확대를 근거로 실적 전망을 상향했다. 다만 단기 주가 변동성과 공급 경쟁은 위험 요인으로 꼽힌다.',
        '2026-07-13T01:00:00Z',
        'DEMO',
        'demo-hash-000660-1'
    ),
    (
        (SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '000660'),
        'demo-news-000660-2',
        '차세대 메모리 투자 확대, 공급망 협력 강화',
        'FinWatch Demo News',
        'https://example.com/news/demo-news-000660-2',
        '<div>국내 반도체 기업들이 차세대 메모리 생산 능력을 확대하고 있다.</div> SK하이닉스는 주요 장비 및 소재 기업과 공급망 협력을 강화하며 생산 안정성을 높일 계획이다. 시장은 투자 확대가 중장기 성장으로 연결될지 주목하고 있다.',
        '2026-07-12T05:30:00Z',
        'DEMO',
        'demo-hash-000660-2'
    ),
    (
        (SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '000660'),
        'demo-news-000660-3',
        '메모리 가격 반등 기대와 단기 변동성 공존',
        'FinWatch Demo News',
        'https://example.com/news/demo-news-000660-3',
        '<p>메모리 재고 조정이 진행되면서 하반기 가격 반등 기대가 커지고 있다.</p> 수요 회복 속도와 환율 변동은 실적에 영향을 줄 수 있다. 투자자는 업황 지표와 기업 공시를 함께 확인할 필요가 있다.',
        '2026-07-11T07:20:00Z',
        'DEMO',
        'demo-hash-000660-3'
    );

