ALTER TABLE news_articles ADD COLUMN canonical_url VARCHAR(1000);
ALTER TABLE news_articles ADD COLUMN content_source VARCHAR(40) NOT NULL DEFAULT 'METADATA_ONLY';
ALTER TABLE news_articles ADD COLUMN rights_profile VARCHAR(40) NOT NULL DEFAULT 'METADATA_ONLY';
ALTER TABLE news_articles ADD COLUMN extractor_version VARCHAR(50);
ALTER TABLE news_articles ADD COLUMN fetched_at TIMESTAMP WITH TIME ZONE;
ALTER TABLE news_articles ADD COLUMN updated_at TIMESTAMP WITH TIME ZONE;

UPDATE news_articles
SET canonical_url = url,
    content_source = 'PROVIDER_SUMMARY',
    rights_profile = 'STORE_FOR_AI',
    extractor_version = 'demo-seed-v1',
    fetched_at = created_at,
    updated_at = created_at
WHERE source = 'DEMO' AND content IS NOT NULL;

CREATE TABLE source_policies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host VARCHAR(255) NOT NULL,
    path_prefix VARCHAR(500) NOT NULL,
    fetch_mode VARCHAR(40) NOT NULL,
    rights_profile VARCHAR(40) NOT NULL,
    content_source VARCHAR(40) NOT NULL,
    min_interval_ms INTEGER NOT NULL,
    user_agent_required BOOLEAN NOT NULL,
    enabled BOOLEAN NOT NULL,
    review_reference VARCHAR(1000) NOT NULL,
    reviewed_at DATE NOT NULL,
    CONSTRAINT uk_source_policy_host_path UNIQUE (host, path_prefix),
    CONSTRAINT ck_source_policy_interval CHECK (min_interval_ms >= 0)
);

INSERT INTO source_policies (
    host, path_prefix, fetch_mode, rights_profile, content_source,
    min_interval_ms, user_agent_required, enabled, review_reference, reviewed_at
)
VALUES
    (
        'www.sec.gov', '/Archives/edgar/data/', 'ALLOWLIST_FETCH', 'STORE_FOR_AI',
        'OFFICIAL_DISCLOSURE', 100, TRUE, TRUE,
        'https://www.sec.gov/search-filings/edgar-search-assistance/accessing-edgar-data', DATE '2026-07-13'
    ),
    (
        'sec.gov', '/Archives/edgar/data/', 'ALLOWLIST_FETCH', 'STORE_FOR_AI',
        'OFFICIAL_DISCLOSURE', 100, TRUE, TRUE,
        'https://www.sec.gov/search-filings/edgar-search-assistance/accessing-edgar-data', DATE '2026-07-13'
    ),
    (
        'opendart.fss.or.kr', '/api/document.xml', 'API_CONTENT', 'STORE_FOR_AI',
        'OFFICIAL_DISCLOSURE', 1000, FALSE, TRUE,
        'https://opendart.fss.or.kr/guide/main.do?apiGrpCd=DS001', DATE '2026-07-13'
    );

INSERT INTO news_articles (
    stock_id, external_id, title, publisher, url, content, published_at, source,
    content_hash, canonical_url, content_source, rights_profile, created_at, updated_at
)
VALUES (
    (SELECT id FROM stocks WHERE market = 'KRX' AND symbol = '000660'),
    'demo-news-000660-metadata-only',
    '외부 뉴스 검색 결과 예시: 원문 링크만 제공',
    'FinWatch Metadata Demo',
    'https://example.com/news/metadata-only',
    NULL,
    '2026-07-10T02:00:00Z',
    'DEMO',
    NULL,
    'https://example.com/news/metadata-only',
    'METADATA_ONLY',
    'METADATA_ONLY',
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);
